KEY_IP_LIGHTPATH_CAPACITY = "IP_LIGHTPATH_CAPACITY"
KEY_IP_LINK_UTILIZATION = "IP_LINK_UTILIZATION"

KEY_LINK_LENGTH = "LINK_LENGTH"

KEY_CDN_ASSIGNMENT_LAYER = "CDN_ASSIGNMENT"
KEY_IP_LINK_LAYER = "IP_LINKS"
KEY_IP_LINK_LAYER_FULL = "IP_LINKS_FULL"
KEY_IP_CONNECTIVITY = "IP_CONNECTIVITY"
KEY_RECONF_FRACTION_IP = "RECONF_FRACTION_IP"
KEY_RECONF_FRACTION_IP_W_OPT = "KEY_RECONF_FRACTION_IP_W_OPT"

BIG_M = 1000

MIN_DEMAND = 1e-2
